-- EFT S9 Eduardo Stegmaier

-------------------------------------
-- Caso 1: Estrategia de seguridad
-------------------------------------
--Ejecuta USUARIO ADMIN
SHOW USER;

------------------
--Crear Usuarios 
------------------

--Usuario  PRY2205_EFT (Owner)(Caso 3)
CREATE USER PRY2205_EFT 
IDENTIFIED BY "contraseña.Fuerte$ETF111"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;   

GRANT CREATE SESSION TO PRY2205_EFT;

GRANT 
    CREATE TABLE, 
    CREATE VIEW,
    CREATE SEQUENCE, 
    CREATE SYNONYM,
    CREATE PUBLIC SYNONYM,
    CREATE ANY INDEX
TO PRY2205_EFT;


--Usuario PRY2205_EFT_DES (Caso 2)
CREATE USER PRY2205_EFT_DES IDENTIFIED BY "Contraseña$Desarrollo111"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;   

GRANT CREATE SESSION TO PRY2205_EFT_DES;

-- Usuario PRY2205_EFT_CON (Caso 2/Caso 3)
CREATE USER PRY2205_EFT_CON IDENTIFIED BY "Contraseña$Consulta111"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;   

GRANT CREATE SESSION TO PRY2205_EFT_CON;

---------------
-- Crear Roles
---------------

DROP ROLE PRY2205_ROL_D;
DROP ROLE PRY2205_ROL_C;

-- Rol  PRY2205_ROL_D
CREATE ROLE PRY2205_ROL_D;
GRANT 
    CREATE USER,
    CREATE SESSION,
    CREATE VIEW
TO PRY2205_ROL_D;

-- Rol PRY2205_ROL_C
CREATE ROLE PRY2205_ROL_C;
GRANT CREATE SESSION TO PRY2205_ROL_C;

--Asignar roles
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

--------------------
-- Crear Sinonimos
--------------------

-- Ejecuta USUARIO PRY2205_EFT
SHOW USER;

CREATE PUBLIC SYNONYM PROF FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM S_PROFESION FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM S_ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM RANGOS FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE PUBLIC SYNONYM CARTOLA FOR PRY2205_EFT.CARTOLA_PROFESIONALES;
CREATE PUBLIC SYNONYM EMP FOR PRY2205_EFT.EMPRESA;
CREATE PUBLIC SYNONYM ASE FOR PRY2205_EFT.ASESORIA;

-- Damos GRANT a ROL D / C a Sinonimos
GRANT SELECT ON PROF TO PRY2205_ROL_D;
GRANT SELECT ON S_PROFESION TO PRY2205_ROL_D;
GRANT SELECT ON S_ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON RANGOS TO PRY2205_ROL_D;
GRANT SELECT ON CARTOLA TO PRY2205_ROL_D;

GRANT INSERT ON CARTOLA TO PRY2205_ROL_D;

GRANT SELECT ON CARTOLA TO PRY2205_ROL_C;


-------------------------------------
--  Caso 2: Creación de Informe
-------------------------------------

-- Ejecuta  Usuario PRY2205_EFT_DES
SHOW USER;

--Vaciar Tabla
DELETE FROM CARTOLA_PROFESIONALES;
COMMIT;

--Insertar datos en tabla Cartola Profesionales
INSERT INTO CARTOLA(
    RUT_PROFESIONAL,
    NOMBRE_PROFESIONAL,
    PROFESION,
    ISAPRE,
    SUELDO_BASE,
    PORC_COMISION_PROFESIONAL,
    VALOR_TOTAL_COMISION,
    PORCENTATE_HONORARIO,
    BONO_MOVILIZACION,
    TOTAL_PAGAR
)
SELECT
    p.RUTPROF                     AS "RUT_PROFESIONAL",
    INITCAP(LOWER(p.NOMPRO)) || ' ' || INITCAP(LOWER(p.APPPRO)) || ' ' || INITCAP(LOWER(p.APMPRO)) AS "NOMBRE_PROFESIONAL",
    pp.NOMPROFESION               AS "PROFESION",
    i.NOMISAPRE                   AS "ISAPRE",
    p.SUELDO                      AS "SUELDO_BASE",
    NVL(p.COMISION, 0)            AS "PORC_COMISION_PROFESIONAL",
    NVL(p.SUELDO * p.COMISION, 0) AS "VALOR_TOTAL_COMISION",
    (SELECT
         (HONOR_PCT/100) * p.SUELDO FROM RANGOS 
        WHERE p.SUELDO BETWEEN S_MIN AND S_MAX
        ) AS "PORCENTATE_HONORARIO",
    (CASE
        WHEN p.IDTCONTRATO = 1 THEN 150000
        WHEN p.IDTCONTRATO = 2 THEN 120000
        WHEN p.IDTCONTRATO = 3 THEN 60000
        WHEN p.IDTCONTRATO = 4 THEN 50000
        ELSE 0
    END) AS "BONO_MOVILIZACION",
    P.SUELDO 
    +  NVL(p.SUELDO * p.COMISION, 0) 
    +  (SELECT (HONOR_PCT/100) * p.SUELDO FROM RANGOS 
        WHERE p.SUELDO BETWEEN S_MIN AND S_MAX)
    +  (CASE
        WHEN p.IDTCONTRATO = 1 THEN 150000
        WHEN p.IDTCONTRATO = 2 THEN 120000
        WHEN p.IDTCONTRATO = 3 THEN 60000
        WHEN p.IDTCONTRATO = 4 THEN 50000
        ELSE 0 END) AS "TOTAL_PAGAR"

FROM PROF p
LEFT JOIN S_PROFESION pp USING(IDPROFESION)
LEFT JOIN S_ISAPRE i USING(IDISAPRE)
;

COMMIT;

--Revisar tabla con USUARIO CONSULTA
SELECT * FROM CARTOLA
ORDER BY PROFESION, SUELDO_BASE DESC, PORC_COMISION_PROFESIONAL, RUT_PROFESIONAL
;


-------------------------------------------
-- Caso 3: Optimización de sentencias SQL
-------------------------------------------

-- Ejecuta USUARIO PRY2205_EFT
SHOW USER;

CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
    REPLACE(TO_CHAR(e.RUT_EMPRESA,'FM99G999G999'), ',','.') || '-' || e.DV_EMPRESA AS "RUT_EMPRESA",
    UPPER(e.NOMEMPRESA)                                               AS "NOMBRE_EMPRESA",
    e.IVA_DECLARADO                                                   AS "IVA",
    ROUND(MONTHS_BETWEEN(SYSDATE, e.FECHA_INICIACION_ACTIVIDADES)/12) AS "ANIOS_EXISTENCIA",
    ROUND(COUNT(a.IDEMPRESA)/12)                                      AS "TOTAL_ASESORIAS_ANUALES",
    ROUND((e.IVA_DECLARADO * ROUND(COUNT(a.IDEMPRESA)/12) )/100)      AS "DEVOLUCION_IVA",
    (CASE
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) > 5 THEN 'CLIENTE PREMIUM'
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) BETWEEN 3 AND 5 THEN 'CLIENTE'
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) BETWEEN 1 AND 2 THEN 'CLIENTE POCO CONCURRIDO'
        ELSE ' '
    END) AS "TIPO_CLIENTE",
    (CASE 
        --CLIENTE PREMIUM
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) >= 7 THEN '1 ASESORIA GRATIS'
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) = 6 THEN '1 ASESORIA 40% DE DESCUENTO'
        --CLIENTE
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) = 5 THEN '1 ASESORIA 30% DE DESCUENTO'
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) BETWEEN 3 AND 4 THEN '1 ASESORIA 20% DE DESCUENTO'
        --CLIENTE POCO CONCURRIDO
        WHEN ROUND(COUNT(a.IDEMPRESA)/12) BETWEEN 1 AND 2 THEN 'CAPTAR CLIENTE'
        ELSE ' '
    END) AS "CORRESPONDE" 
FROM EMP e
LEFT JOIN ASE a 
    ON  a.IDEMPRESA = e.IDEMPRESA 
    AND (EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 )
GROUP BY
    e.RUT_EMPRESA, e.DV_EMPRESA, e.NOMEMPRESA, e.IVA_DECLARADO, e.FECHA_INICIACION_ACTIVIDADES
HAVING 
    ROUND(COUNT(a.IDEMPRESA)/12) > 0
;

--Sinonimo Vista
CREATE PUBLIC SYNONYM VISTA_EMPRESAS
FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

GRANT SELECT ON VISTA_EMPRESAS TO PRY2205_ROL_C;

--Revisar Vista con USUARIO CONSULTA
SELECT * FROM VISTA_EMPRESAS
ORDER BY NOMBRE_EMPRESA ASC;

---------------------------------------
--   Caso 3.2: Creación de Índices
---------------------------------------

-- Ejecuta USUARIO PRY2205_EFT
SHOW USER;

DROP INDEX IDX_IDEMPRESA;

CREATE INDEX IDX_IDEMPRESA
    ON PRY2205_EFT.ASESORIA(IDEMPRESA,FIN);

-- Ver Plan
EXPLAIN PLAN FOR
SELECT *
FROM VW_EMPRESAS_ASESORADAS;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);