-- S6 - Comercial Manager Consultants - Eduardo Stegmaier

-- Caso 1:  Reportería de Asesorías

SELECT
    p.ID_PROFESIONAL AS "ID",
    INITCAP(LOWER(p.APPATERNO)) || ' ' || INITCAP(LOWER(p.APMATERNO)) || ' ' || INITCAP(LOWER(p.NOMBRE)) AS "PROFESIONAL",
    --
    --BANCA
    COUNT((CASE WHEN COD_SECTOR=3 THEN 1 ELSE NULL END)) AS "NRO ASESORIA BANCA",
    TO_CHAR(
        (SELECT 
            SUM(a.HONORARIO ) FROM ASESORIA a
            INNER JOIN EMPRESA E USING(COD_EMPRESA)
            WHERE E.COD_SECTOR = 3 AND a.ID_PROFESIONAL = p.ID_PROFESIONAL),
        'L99G999G999') AS "MONTO_TOTAL_BANCA",
    --
    --RETAIL
    COUNT((CASE WHEN COD_SECTOR=4 THEN 1 ELSE NULL END)) AS "NRO ASESORIA RETAIL",
    TO_CHAR(
        (SELECT 
            SUM(a.HONORARIO ) FROM ASESORIA a
            INNER JOIN EMPRESA E USING(COD_EMPRESA)
            WHERE E.COD_SECTOR = 4 AND a.ID_PROFESIONAL = p.ID_PROFESIONAL),
        'L99G999G999') AS "MONTO_TOTAL_RETAIL",
    --    
    --TOTAL
    COUNT((CASE WHEN COD_SECTOR=3 OR COD_SECTOR=4 THEN 1 
                ELSE NULL END)) AS "TOTAL ASESORIAS",
    TO_CHAR(
        (SELECT 
            SUM(a.HONORARIO ) FROM ASESORIA a
            INNER JOIN EMPRESA E USING(COD_EMPRESA)
            WHERE (E.COD_SECTOR = 3 OR E.COD_SECTOR = 4) AND a.ID_PROFESIONAL = p.ID_PROFESIONAL),
        'L999G999G999') AS "TOTAL HONORARIOS"
FROM
    PROFESIONAL p
INNER JOIN ASESORIA a  ON a.ID_PROFESIONAL = p.ID_PROFESIONAL
INNER JOIN EMPRESA e   USING(COD_EMPRESA)
INNER JOIN SECTOR s    USING(COD_SECTOR)
WHERE
    -- Intersect sector 3 y 4
    P.ID_PROFESIONAL IN 
        (SELECT DISTINCT aa.id_profesional FROM asesoria aa 
        INNER JOIN empresa ee USING(cod_empresa)
        WHERE ee.cod_sector = 3

        INTERSECT

        SELECT DISTINCT aa.id_profesional FROM asesoria aa
        INNER JOIN empresa ee USING(cod_empresa)
        WHERE ee.cod_sector = 4)   
GROUP BY
    P.ID_PROFESIONAL, p.NOMBRE, p.APPATERNO, p.APMATERNO
ORDER BY
    p.ID_PROFESIONAL ASC
;



-------------------------------------------
--Caso 2: resumen Honorarios
-------------------------------------------

--Eliminar Tabla
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE REPORTE_MES PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

--Crear Tabla con Select
CREATE TABLE REPORTE_MES AS
SELECT
    p.ID_PROFESIONAL        AS "ID_PROF",
    INITCAP(LOWER(p.APPATERNO)) || ' ' || INITCAP(LOWER(p.APMATERNO)) || ' ' || INITCAP(LOWER(p.NOMBRE)) AS "NOMBRE_PROFESIONAL",
    pp.NOMBRE_PROFESION     AS "NOMBRE PROFESION",
    c.NOM_COMUNA            AS "NOM_COMUNA",
    COUNT(a.COD_EMPRESA)    AS "NRO_ASESORIAS",
    ROUND(SUM(a.HONORARIO)) AS "MONTO_TOTAL_HONORARIOS",
    ROUND(AVG(a.HONORARIO)) AS "PROMEDIO HONORARIO",
    ROUND(MIN(a.HONORARIO)) AS "HONORARIO_MINIMO",
    ROUND(MAX(a.HONORARIO)) AS "HONORARIO_MAXIMO"
FROM
    PROFESIONAL p
INNER JOIN PROFESION pp ON pp.COD_PROFESION = p.COD_PROFESION
INNER JOIN COMUNA    c  ON c.COD_COMUNA = p.COD_COMUNA
INNER JOIN ASESORIA  a  ON a.ID_PROFESIONAL = p.ID_PROFESIONAL
WHERE
    EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1 
    AND (EXTRACT(MONTH FROM a.FIN_ASESORIA) = 4)
GROUP BY
    p.ID_PROFESIONAL, p.NOMBRE, p.APPATERNO, p.APMATERNO, pp.NOMBRE_PROFESION, c.NOM_COMUNA
ORDER BY
    p.ID_PROFESIONAL ASC
;

-- Commit despues de CREATE TABLE
COMMIT;

--Ver Tabla
SELECT * FROM REPORTE_MES; 

---------------------------------------------
--Caso 3: Modificacion de Honorarios
---------------------------------------------

--Actualizar tabla
UPDATE PROFESIONAL p
SET SUELDO = CASE
    WHEN (SELECT NVL(SUM(a.honorario), 0) FROM ASESORIA a
          WHERE a.ID_PROFESIONAL = p.ID_PROFESIONAL
            AND EXTRACT(MONTH FROM a.FIN_ASESORIA) = 3
            AND EXTRACT(YEAR  FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
         ) < 1000000
    THEN SUELDO * 1.10 ELSE SUELDO * 1.15
END
WHERE EXISTS (
    SELECT 1 FROM ASESORIA a
    WHERE a.ID_PROFESIONAL = p.ID_PROFESIONAL
      AND EXTRACT(MONTH FROM a.FIN_ASESORIA) = 3
      AND EXTRACT(YEAR  FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
);

-- Commit despues de UPDATE
COMMIT;  

--Revisar Tabla
SELECT 
    SUM(a.HONORARIO) AS "HONORARIO",
    p.ID_PROFESIONAL AS "ID_PROFESIONAL",
    P.NUMRUN_PROF AS "NUMRUN_PROF",
    p.SUELDO AS "SUELDO"
FROM PROFESIONAL p 
INNER JOIN ASESORIA a ON a.ID_PROFESIONAL = p.ID_PROFESIONAL
WHERE 
    EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1 
    AND (EXTRACT(MONTH FROM a.FIN_ASESORIA) = 3)
GROUP BY
    p.ID_PROFESIONAL, P.NUMRUN_PROF, p.SUELDO
ORDER BY 
    ID_PROFESIONAL ASC
;
