-- S5 FinanCorp - Grupo 9

-- Caso 1: Listado de Clientes

SELECT
    REPLACE(TO_CHAR(c.NUMRUN,'99G999G999'), ',','.') || '-' || c.DVRUN AS "RUT Cliente",
    INITCAP(LOWER(c.PNOMBRE)) || ' ' || INITCAP(LOWER(c.APPATERNO))    AS "Nombre Cliente",
    UPPER(po.NOMBRE_PROF_OFIC)                  AS "Profesion Cliente",
    TO_CHAR(c.FECHA_INSCRIPCION, 'DD-MON-YYYY') AS "Fecha de Inscripcion",
    c.DIRECCION                                 AS "Direccion Cliente"
FROM
    CLIENTE c
LEFT JOIN PROFESION_OFICIO po
    ON po.COD_PROF_OFIC = c.COD_PROF_OFIC
WHERE 
    (UPPER(po.NOMBRE_PROF_OFIC) = 'CONTADOR'
    OR UPPER(po.NOMBRE_PROF_OFIC) = 'VENDEDOR')
    AND c.COD_TIPO_CLIENTE =
        (SELECT COD_TIPO_CLIENTE
         FROM   TIPO_CLIENTE 
         WHERE  UPPER(NOMBRE_TIPO_CLIENTE) = 'TRABAJADORES DEPENDIENTES')
    AND EXTRACT(YEAR FROM c.FECHA_INSCRIPCION) >
        (SELECT ROUND(AVG(EXTRACT(YEAR FROM FECHA_INSCRIPCION)))
        FROM CLIENTE 
        )
        
ORDER BY
    NUMRUN || DVRUN ; 
--


-- Caso 2: Aumento de Credito

--Borrar tabla
DROP TABLE CLIENTES_CUPOS_COMPRA CASCADE CONSTRAINTS;

--Crear Tabla
CREATE TABLE CLIENTES_CUPOS_COMPRA AS
SELECT 
    cc.RUT_CLIENTE,
    cc.EDAD,
    cc.CUPO_DISPONIBLE_COMPRA,
    cc.TIPO_CLIENTE 

FROM    (
    SELECT
        TO_CHAR(NUMRUN) || '-' || TO_CHAR(c.DVRUN) AS "RUT_CLIENTE",
        EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM c.FECHA_NACIMIENTO) AS "EDAD",
        TO_CHAR(t.CUPO_DISP_COMPRA, 'L9G999G999') AS "CUPO_DISPONIBLE_COMPRA",
        UPPER(tc.NOMBRE_TIPO_CLIENTE) AS "TIPO_CLIENTE"
    FROM CLIENTE c
    LEFT JOIN TIPO_CLIENTE tc USING (COD_TIPO_CLIENTE)
    LEFT JOIN TARJETA_CLIENTE t USING(NUMRUN)
    WHERE t.CUPO_DISP_COMPRA >=
        (
        SELECT MAX(CUPO_DISP_COMPRA) --Max cupo disponible año anterior
        FROM   TARJETA_CLIENTE t_ant
        WHERE  EXTRACT(YEAR FROM t_ant.FECHA_SOLIC_TARJETA) = EXTRACT(YEAR FROM SYSDATE) - 1
        )
    ORDER BY
        EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM c.FECHA_NACIMIENTO) ASC
    ) cc;