--S8 DBMS COLLEGE - Eduardo Stegmaier

-------------------------------------
-- Caso 1: Estrategia de seguridad
-------------------------------------
--USUARIO ADMIN

-- Crear Usuarios 
CREATE USER PRY2205_USER1 IDENTIFIED BY "contraseñaUSER1"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON DATA;

CREATE USER PRY2205_USER2 IDENTIFIED BY "contraseñaUSER2"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER1;
GRANT CREATE SESSION TO PRY2205_USER2;
--
--USUARIO ADMIN

-- Crear Roles
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;

GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SEQUENCE TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;
GRANT CREATE ANY INDEX TO PRY2205_ROL_D;

--
GRANT CREATE SESSION TO PRY2205_ROL_P;
GRANT CREATE TABLE TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.LIBRO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_ROL_P;
--
GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;

--Crear Sinonimos
-- USUARIO USER 1

CREATE PUBLIC SYNONYM LIB
FOR PRY2205_USER1.LIBRO;

CREATE PUBLIC SYNONYM EJEM
FOR PRY2205_USER1.EJEMPLAR;

CREATE PUBLIC SYNONYM PRES
FOR PRY2205_USER1.PRESTAMO;



-------------------------------------
-- Caso 2: Creación de Informe
-------------------------------------

--USUARIO USER2

--Crear sequencia
CREATE SEQUENCE SEQ_CONTROL_STOCK;

CREATE TABLE CONTROL_STOCK_LIBROS AS
SELECT
    SEQ_CONTROL_STOCK.NEXTVAL AS ID_CONTROL,
    l.LIBROID AS "LIBRO_ID",
    l.NOMBRE_LIBRO AS "NOMBRE_LIBRO",
    COUNT(DISTINCT e.EJEMPLARID) AS "TOTAL_EJEMPLARES",
    (SELECT COUNT(DISTINCT PRESTAMOID) FROM PRES 
        WHERE LIBROID = l.LIBROID
        )AS "EN_PRESTAMO",
    COUNT(DISTINCT e.EJEMPLARID) -  
    (SELECT COUNT(DISTINCT PRESTAMOID) FROM PRES 
        WHERE LIBROID = l.LIBROID
        ) AS "DISPONIBLES",
    --AS "PORCENTAJE PRESTAMO",
    (CASE 
        WHEN COUNT(e.EJEMPLARID) >= 2 THEN 'S'
        ELSE 'N'
    END)AS "STOCK_CRITICO"
FROM 
    LIB l 
INNER JOIN EJEM e ON e.LIBROID = l.LIBROID
LEFT JOIN PRES p  ON p.EJEMPLARID = e.EJEMPLARID --AND p.LIBROID = e.LIBROID
WHERE
    EXTRACT(MONTH FROM SYSDATE) = EXTRACT(MONTH FROM p.FECHA_TERMINO)
    AND EXTRACT(YEAR FROM SYSDATE) - 2 = EXTRACT(YEAR FROM p.FECHA_TERMINO)
    AND p.EMPLEADOID IN (190, 180, 150)
GROUP BY
    l.LIBROID, l.NOMBRE_LIBRO
ORDER BY 
    l.LIBROID
;

--Revisar tabla
SELECT * FROM CONTROL_STOCK_LIBROS;


------------------------------------------
-- Caso 3: Optimización de sentencias SQL
------------------------------------------
--USUARIO USER 1

--Caso 3.1: Creación de Vista

CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT
    p.PRESTAMOID                            AS "ID_PRESTAMO",
    INITCAP(LOWER(a.NOMBRE)) || ' ' || INITCAP(LOWER(a.APATERNO)) AS "NOMBRE_ALUMNO",
    c.DESCRIPCION                           AS "NOMBRE_CARRERA",
    p.LIBROID                               AS "ID_LIBRO",
    TO_CHAR(l.PRECIO, 'FML999G999')         AS "VALOR_LIBRO",
    TO_CHAR(p.FECHA_TERMINO, 'DD/MM/YYYY')  AS "FECHA_TERMINO",
    TO_CHAR(p.FECHA_ENTREGA, 'DD/MM/YYYY')  AS "FECHA ENTREGA",
    ROUND((MONTHS_BETWEEN(p.FECHA_ENTREGA, p.FECHA_TERMINO)*31)) AS "DIAS_ATRASO",
    TO_CHAR(ROUND(
        l.PRECIO * 0.03 * (MONTHS_BETWEEN(p.FECHA_ENTREGA, p.FECHA_TERMINO)*31) 
    ), 'FML999G999')                        AS "VALOR_MULTA",
    NVL(rm.PORC_REBAJA_MULTA/100, 0)        AS "PORCENTAJE_REBAJA_MULTA",
    TO_CHAR(ROUND (
        (1 - NVL(rm.PORC_REBAJA_MULTA/100, 0))
        * l.PRECIO * 0.03 * (MONTHS_BETWEEN(p.FECHA_ENTREGA, p.FECHA_TERMINO)*31) 
    ), 'FML999G999')                        AS "VALOR_REBAJADO"
FROM
    PRES p 
INNER JOIN ALUMNO a ON a.ALUMNOID = p.ALUMNOID
LEFT JOIN CARRERA c USING(CARRERAID)
INNER JOIN EJEM e ON
    e.LIBROID = p.LIBROID AND e.EJEMPLARID = p.EJEMPLARID
INNER JOIN LIB l ON
    l.LIBROID = e.LIBROID
LEFT JOIN REBAJA_MULTA rm USING (CARRERAID)
WHERE
    EXTRACT(YEAR FROM p.FECHA_TERMINO) = EXTRACT(YEAR FROM SYSDATE) - 2
    AND  MONTHS_BETWEEN(p.FECHA_ENTREGA, p.FECHA_TERMINO) > 0
ORDER BY
    p.FECHA_ENTREGA DESC
;

--Caso 3.2: Creación de Índices
--USUARIO USER 1

--Crear Index
CREATE INDEX IDX_PRESTAMO
ON PRES (LIBROID, EJEMPLARID);
