--S7 SpaceLive Grupo 9

-----------------------------------------
--Caso 1: Bonificación de Trabajadores
-----------------------------------------


--Dar permisos
GRANT SELECT ON TRABAJADOR TO PRY2205_S7;
GRANT SELECT ON BONO_ANTIGUEDAD TO PRY2205_S7;
GRANT SELECT ON TICKETS_CONCIERTO TO PRY2205_S7;

--Crear Sinonimos
CREATE SYNONYM TRAB FOR TRABAJADOR;
CREATE SYNONYM BONO FOR BONO_ANTIGUEDAD;
CREATE SYNONYM TICKET FOR TICKETS_CONCIERTO;

--
--En caso de requerir reingresar datos
--Reseteamos la secuencia 
DROP SEQUENCE seq_det_bonif;
CREATE SEQUENCE seq_det_bonif START WITH 100 INCREMENT BY 10 NOCACHE NOCYCLE;

--Vaciamos tabla 
DELETE FROM DETALLE_BONIFICACIONES_TRABAJADOR;
COMMIT;
--

--Insertar datos en Tabla con Select
INSERT INTO DETALLE_BONIFICACIONES_TRABAJADOR 
SELECT
    seq_det_bonif.NEXTVAL                      AS "NUM", -- usamos secuencia seq_det_bonif
    t.NUMRUT || '-' || t.DVRUT                 AS "RUT",
    INITCAP(LOWER(t.NOMBRE)) || ' ' || INITCAP(LOWER(t.APPATERNO)) || ' ' || INITCAP(LOWER(t.APMATERNO)) AS "NOMBRE_TRABAJADOR",
    TO_CHAR(t.SUELDO_BASE,'FML9G999G999')      AS "SUELDO_BASE", --FM ajusta el largo quitando espacios en blanco
    NVL(TO_CHAR(ti.NRO_TICKET), 'No hay info') AS "NUM_TICKET",
    t.DIRECCION                                AS "DIRECCION",
    i.NOMBRE_ISAPRE                            AS "SISTEMA_SALUD",
    TO_CHAR(NVL(ti.MONTO_TICKET, 0), 'FML9G999G999') AS "MONTO",
    TO_CHAR(NVL((CASE
        WHEN ti.MONTO_TICKET <= 50000 THEN 0
        WHEN ti.MONTO_TICKET BETWEEN 50001 AND 100000 THEN 0.05*ti.MONTO_TICKET
        WHEN ti.MONTO_TICKET > 100000 THEN 0.07*ti.MONTO_TICKET
    END), 0),'FML99G999G999') AS "BONIF_X_TICKET",
    TO_CHAR(NVL((CASE
        WHEN ti.MONTO_TICKET <= 50000 THEN 0                                    + t.SUELDO_BASE 
        WHEN ti.MONTO_TICKET BETWEEN 50001 AND 100000 THEN 0.05*ti.MONTO_TICKET + t.SUELDO_BASE
        WHEN ti.MONTO_TICKET > 100000 THEN 0.07*ti.MONTO_TICKET                 + t.SUELDO_BASE
    END), t.SUELDO_BASE),'FML99G999G999') AS "SIMULACION_X_TICKET",
        
    TO_CHAR(t.SUELDO_BASE * (1 + b.PORCENTAJE),'FML99G999G999') AS "SIMULACION_ANTIGUEDAD"
FROM
    TRAB t
LEFT JOIN ISAPRE i  ON i.COD_ISAPRE = t.COD_ISAPRE
LEFT JOIN TICKET ti ON ti.NUMRUT_T = t.NUMRUT
RIGHT JOIN BONO b 
    ON MONTHS_BETWEEN(SYSDATE, t.FECING)/12 BETWEEN b.LIMITE_INFERIOR AND b.LIMITE_SUPERIOR
WHERE
    i.PORC_DESCTO_ISAPRE > 4 AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM t.FECNAC) < 50
;

--Commit INSERT
COMMIT;

--Revisar Tabla DETALLE_BONIFICACIONES_TRABAJADOR
SELECT * FROM DETALLE_BONIFICACIONES_TRABAJADOR
ORDER BY MONTO DESC, NOMBRE_TRABAJADOR ASC;


---------------------------------------------
--Caso 2: Vistas
---------------------------------------------


--Etapa 1: Vista V_AUMENTOS_ESTUDIOS

--crear sinonimo extra
GRANT SELECT ON TIPO_TRABAJADOR TO PRY2205_S7;
CREATE SYNONYM TIPO FOR TIPO_TRABAJADOR;

--Crear Vista con Select
CREATE OR REPLACE VIEW V_AUMENTOS_ESTUDIOS AS
SELECT
    REPLACE(TO_CHAR(t.NUMRUT,'FM99G999G999'), ',','.')                                                   AS "RUT_TRABAJADOR",
    INITCAP(LOWER(t.NOMBRE)) || ' ' || INITCAP(LOWER(t.APPATERNO)) || ' ' || INITCAP(LOWER(t.APMATERNO)) AS "TRABAJADOR",
    be.DESCRIP                                      AS "DESCRIP",
    LPAD(be.PORC_BONO, 7, 0)                        AS "PCT_ESTUDIOS",
    t.SUELDO_BASE                                   AS "SUELDO_ACTUAL",
    ROUND(t.SUELDO_BASE*(be.PORC_BONO/100))         AS "AUMENTO",
    TO_CHAR(ROUND(t.SUELDO_BASE*( 1 + (be.PORC_BONO/100) )), 'FML9G999G999') AS "SUELDO_AUMENTADO"
FROM 
    TRAB t
LEFT JOIN TIPO tt ON tt.ID_CATEGORIA = t.ID_CATEGORIA_T
LEFT JOIN BONO_ESCOLAR be ON be.ID_ESCOLAR = t.ID_ESCOLARIDAD_T
WHERE
    EXISTS((SELECT 1 FROM ASIGNACION_FAMILIAR
     GROUP BY NUMRUT_T
     HAVING NUMRUT_T = t.NUMRUT AND COUNT(NUMRUT_CARGA) BETWEEN 1 AND 2
    ))
    OR tt.DESC_CATEGORIA = 'CAJERO'
ORDER BY
    be.PORC_BONO ASC, t.NOMBRE || t.APPATERNO || t.APMATERNO ASC
;

--Revisar Vista
SELECT * FROM V_AUMENTOS_ESTUDIOS ORDER BY 4, 1;


--
-- Etapa 2: Optimización de consultas

--Select 
SELECT t.NUMRUT, t.FECNAC, t.NOMBRE, t.APPATERNO, t.APMATERNO
FROM TRABAJADOR t JOIN ISAPRE i 
    ON ( i.COD_ISAPRE = t.COD_ISAPRE)
WHERE t.APMATERNO = 'CASTILLO'
ORDER BY 3;

--Crear Index
CREATE INDEX IDX_TRAB_ISAPRE
ON TRABAJADOR (COD_ISAPRE, APMATERNO);

--Select
SELECT t.NUMRUT, t.FECNAC, t.NOMBRE, t.APPATERNO, t.APMATERNO
FROM TRABAJADOR t JOIN ISAPRE i 
    ON ( i.COD_ISAPRE = t.COD_ISAPRE)
WHERE UPPER(t.APMATERNO) = 'CASTILLO'
ORDER BY 3;

--Crear Index
CREATE INDEX IDX_TRAB_ISAPRE_UPPER
ON TRABAJADOR (COD_ISAPRE, UPPER(APMATERNO));
